version: '3.7'
services:
  app_proxy:
    environment:
      APP_HOST: $APP_HOME_ASSISTANT_IP
      APP_PORT: 8123
      PROXY_AUTH_ADD: 'false'
  server:
    image: homeassistant/home-assistant:2024.4.3@sha256:4f86df601650c74b8689f1be033054ff09567db5dba5bf227ccc406ca4fa88d0
    volumes:
      - ${APP_DATA_DIR}/data:/config
      - /run/dbus:/run/dbus:ro
    networks:
      default:
        ipv4_address: $APP_HOME_ASSISTANT_IP
    restart: on-failure
