version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: $APP_HOME_ASSISTANT_IP
      APP_PORT: 8123
      PROXY_AUTH_ADD: "false"

  server:
    image: homeassistant/home-assistant:2022.11.4
    volumes:
      - ${APP_DATA_DIR}/data:/config
    networks:
      default:
        ipv4_address: $APP_HOME_ASSISTANT_IP
    restart: on-failure
