version: '3.7'
services:
  app_proxy:
    environment:
      APP_HOST: $APP_HOME_ASSISTANT_IP
      APP_PORT: 8123
      PROXY_AUTH_ADD: 'false'
  server:
    image: homeassistant/home-assistant:2023.10.2@sha256:6d91569d89e3343f84306e308e4687036511cae553b3d8d6ee17e18c30d1bdcf
    volumes:
      - ${APP_DATA_DIR}/data:/config
      - /run/dbus:/run/dbus:ro
    networks:
      default:
        ipv4_address: $APP_HOME_ASSISTANT_IP
    restart: on-failure
