version: '3.7'
services:
  app_proxy:
    environment:
      APP_HOST: $APP_HOME_ASSISTANT_IP
      APP_PORT: 8123
      PROXY_AUTH_ADD: 'false'
  server:
    image: homeassistant/home-assistant:2023.3.4@sha256:5ee95ed91a2b1649b9921402e3c06d1ffcb6257261c10dc1d61f38b276d90964
    volumes:
      - ${APP_DATA_DIR}/data:/config
      - /run/dbus:/run/dbus:ro
    networks:
      default:
        ipv4_address: $APP_HOME_ASSISTANT_IP
    restart: on-failure
