version: '3.7'
services:
  app_proxy:
    environment:
      APP_HOST: $APP_HOME_ASSISTANT_IP
      APP_PORT: 8123
      PROXY_AUTH_ADD: 'false'
  server:
    image: homeassistant/home-assistant:2023.8.4@sha256:5970dce5dab73ec4c70be107b799b59e9f47027ac6ec0215d34cf89f664fed9c
    volumes:
      - ${APP_DATA_DIR}/data:/config
      - /run/dbus:/run/dbus:ro
    networks:
      default:
        ipv4_address: $APP_HOME_ASSISTANT_IP
    restart: on-failure
