version: '3.7'
services:
  app_proxy:
    environment:
      APP_HOST: $APP_HOME_ASSISTANT_IP
      APP_PORT: 8123
      PROXY_AUTH_ADD: 'false'
  server:
    image: homeassistant/home-assistant:2024.6.4@sha256:17d159928122e6f374bd39b0e75904522bc7d7c2a64e88b248948734e4c4d444
    volumes:
      - ${APP_DATA_DIR}/data:/config
      - /run/dbus:/run/dbus:ro
    networks:
      default:
        ipv4_address: $APP_HOME_ASSISTANT_IP
    restart: on-failure
