version: '3.7'
services:
  app_proxy:
    environment:
      APP_HOST: $APP_OPENSPEEDTEST_IP
      APP_PORT: 3000
  server:
    image: openspeedtest/latest:v0.0.1@sha256:6d5a39cb0b2b2d505eefcb07f5c3f85e6655521837223e3bce7fe1d114f0404b
    networks:
      default:
        ipv4_address: $APP_OPENSPEEDTEST_IP
    restart: on-failure
