version: '3.7'
services:
  app_proxy:
    environment:
      APP_HOST: $APP_OPENSPEEDTEST_IP
      APP_PORT: 3000
  server:
    image: openspeedtest/latest:v2.0.1@sha256:0b103aa0282f52e24a08aec36240197952bd291f513e590025ffd731a7e7bf9a
    networks:
      default:
        ipv4_address: $APP_OPENSPEEDTEST_IP
    restart: on-failure
