version: '3.7'
services:
  app_proxy:
    environment:
      APP_HOST: $APP_OPENSPEEDTEST_IP
      APP_PORT: 3000
  server:
    image: openspeedtest/latest:v0.0.1@sha256:268d9e2da85674764615d311903d840b0e4efa180b1975e70aca207553b4c353
    networks:
      default:
        ipv4_address: $APP_OPENSPEEDTEST_IP
    restart: on-failure
