version: "3.7"

services:
  app_proxy:
      environment:
        APP_HOST: $APP_OPENSPEEDTEST_IP
        APP_PORT: 3001
        PROXY_AUTH_ADD: "false"

  server:
    image: openspeedtest/latest
    ports:
      - 3001:3000/tcp
    networks:
      default:
        ipv4_address: $APP_OPENSPEEDTEST_IP
    restart: on-failure