version: '3.7'
services:
  app_proxy:
    environment:
      APP_HOST: $APP_OPENSPEEDTEST_IP
      APP_PORT: 3000
  server:
    image: openspeedtest/latest:v0.0.1@sha256:142c467d1575c90e49f396dd2d90a47257d62b35ebd1e34ba5d307b6a1c21d15
    networks:
      default:
        ipv4_address: $APP_OPENSPEEDTEST_IP
    restart: on-failure
