version: '3.7'
services:
  app_proxy:
    environment:
      APP_HOST: $APP_ADGUARD_HOME_IP
      APP_PORT: 3000
      PROXY_AUTH_ADD: 'false'
  server:
    image: adguard/adguardhome:v0.107.27@sha256:09c491f2bbd5d175d671f34ef485283ddc1c8c08435d652ae583b7be3d941be0
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 784:784/udp
      - 853:853/tcp
      - 8853:8853/udp
      - 5443:5443/tcp
      - 5443:5443/udp
    volumes:
      - ${APP_DATA_DIR}/data/work:/opt/adguardhome/work
      - ${APP_DATA_DIR}/data/conf:/opt/adguardhome/conf
    networks:
      default:
        ipv4_address: $APP_ADGUARD_HOME_IP
    restart: on-failure
