version: '3.7'
services:
  app_proxy:
    environment:
      APP_HOST: $APP_ADGUARD_HOME_IP
      APP_PORT: 3498
      PROXY_AUTH_ADD: 'false'
  server:
    image: adguard/adguardhome:v0.107.22
    ports:
      - 67:67/tcp
      - 93:93/udp
      - 345:345/udp
      - 345:345/tcp
      - 9900:9900/udp
      - 5678:5678/tcp
      - 9878:9878/udp
    volumes:
      - ${APP_DATA_DIR}/data/work:/opt/adguardhome/work
      - ${APP_DATA_DIR}/data/conf:/opt/adguardhome/conf
    networks:
      default:
        ipv4_address: $APP_ADGUARD_HOME_IP
    restart: on-failure
