version: '3.7'
services:
  app_proxy:
    environment:
      APP_HOST: $APP_ADGUARD_HOME_IP
      APP_PORT: 3000
      PROXY_AUTH_ADD: 'false'
  server:
    image: adguard/adguardhome:v0.107.43@sha256:4016a420451810959f782d3cbe04c620d83c3431cbb13ae27aabd2921db482a0
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 784:784/udp
      - 853:853/tcp
      - 8853:8853/udp
      - 5443:5443/tcp
      - 5443:5443/udp
    volumes:
      - ${APP_DATA_DIR}/data/work:/opt/adguardhome/work
      - ${APP_DATA_DIR}/data/conf:/opt/adguardhome/conf
    networks:
      default:
        ipv4_address: $APP_ADGUARD_HOME_IP
    restart: on-failure
