version: '3.7'
services:
  app_proxy:
    environment:
      APP_HOST: $APP_ESPHOME_IP
      APP_PORT: 6052
  server:
    image: esphome/esphome:2024.8.3@sha256:dd5fe357aa5c3407e87c4ebe082d0c218cd42db49914f7c265955172f29e6768
    volumes:
      - ${APP_DATA_DIR}/data:/config
      - /dev:/dev
    networks:
      default:
        ipv4_address: $APP_ESPHOME_IP
    restart: on-failure
    device_cgroup_rules:
      - c 188:* rmw
