version: '3.7'
services:
  app_proxy:
    environment:
      APP_HOST: $APP_ESPHOME_IP
      APP_PORT: 6052
  server:
    image: esphome/esphome:2023.5.4@sha256:b3bd3261c1e4ebc3e9dbd510221889f6bea6ab337bfac3b1f0edb3c6a1991365
    volumes:
      - ${APP_DATA_DIR}/data:/config
      - /dev:/dev
    networks:
      default:
        ipv4_address: $APP_ESPHOME_IP
    restart: on-failure
    device_cgroup_rules:
      - c 188:* rmw
