version: '3.7'
services:
  app_proxy:
    environment:
      APP_HOST: $APP_ESPHOME_IP
      APP_PORT: 6052
  server:
    image: esphome/esphome:2023.4.3@sha256:360adf4babb0b2f3caa744f3fe672ae1700e99681fcaf8c09f9fd4d71c8b2337
    volumes:
      - ${APP_DATA_DIR}/data:/config
      - /dev:/dev
    networks:
      default:
        ipv4_address: $APP_ESPHOME_IP
    restart: on-failure
    device_cgroup_rules:
      - c 188:* rmw
