version: '3.7'
services:
  app_proxy:
    environment:
      APP_HOST: $APP_ESPHOME_IP
      APP_PORT: 6052
  server:
    image: esphome/esphome:2023.7.0@sha256:21322f093bef7566e235bacddf6400737a404f5916842be39c54116dbf4f5284
    volumes:
      - ${APP_DATA_DIR}/data:/config
      - /dev:/dev
    networks:
      default:
        ipv4_address: $APP_ESPHOME_IP
    restart: on-failure
    device_cgroup_rules:
      - c 188:* rmw
