version: '3.7'
services:
  app_proxy:
    environment:
      APP_HOST: $APP_ESPHOME_IP
      APP_PORT: 6052
  server:
    image: esphome/esphome:2023.10.6@sha256:5a0276e1b57f231bafd1e75792b6a99d74def8932665acc876a8c34bfe2de8e4
    volumes:
      - ${APP_DATA_DIR}/data:/config
      - /dev:/dev
    networks:
      default:
        ipv4_address: $APP_ESPHOME_IP
    restart: on-failure
    device_cgroup_rules:
      - c 188:* rmw
