name: Auto Update AdGuard Home

env:
  URL: https://api.github.com/repos/AdguardTeam/AdGuardHome/releases/latest
  ID: adguard-home
  NAME: AdGuard Home
  DOCKER: adguard/adguardhome
  ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Fetch the latest version
        run: |
          export LATEST=$(curl -sL ${{ env.URL }} | jq -r ".tag_name")
          echo "::set-env name=LATEST::$LATEST"

      - name: Update the version
        uses: fjogeleit/yaml-update-action@main
        if: ${{ env.LATEST != 'null' }}
        with:
          valueFile: 'shonp40-${{ env.ID }}/umbrel-app.yml'
          changes: |
            {
              "shonp40-${{ env.ID }}/umbrel-app.yml": {
                "version": "${{ env.LATEST }}"
              },
              "shonp40-${{ env.ID }}/docker-compose.yml": {
                "services.server.image": "${{ env.DOCKER }}:${{ env.LATEST }}"
              }
            }
          commitChange: true
          branch: master
          message: 'Updated ${{ env.NAME }} to ${{ env.LATEST }}'