name: Auto Update Home Assistant

env:
  URL: https://api.github.com/repos/home-assistant/core/releases/latest
  ID: home-assistant
  NAME: Home Assistant
  DOCKER: homeassistant/home-assistant

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch the latest version
        run: |
          export LATEST=$(curl -sL ${{ env.URL }} | jq -r ".tag_name")
          echo "::set-env name=LATEST::$LATEST"

      - name: Update docker-compose
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'shonp40-${{ env.ID }}/docker-compose.yml'
          propertyPath: 'services.server.image'
          value: ${{ env.DOCKER }}:${{ env.LATEST }}

      - name: Update the version
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'shonp40-${{ env.ID }}/umbrel-app.yml'
          propertyPath: 'version'
          value: ${{ env.LATEST }}
          commitChange: true
          branch: master
          message: 'Updated ${{ env.NAME }} to ${{ env.LATEST }}'